version: '3'
services:
  #Nginx Service
   webserver:
     image: nginx:latest
     container_name: nginxserver
     restart: unless-stopped
     ports:
       - "8081:80"
       - "443:443"
   #Mysql DB
   db:
     image: mysql:latest
     container_name: mysqlserver
     restart: unless-stopped
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: P@ssw0rd
       MYSQL_DATABASE: MYSQL
       MYSQL_USER: root
  

volumes:
    db_data:
